work around MSVC 2015 error.
an1sym.h(709): error C2440: 'initializing': cannot convert from 'initializer list' to 'guid_t' (compiling source file an1.cc)